jenkinsci/docker-build-step-plugin

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateContainerCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/util/CommandUtils.java
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateContainerCommand/config-detail.jelly
src/test/java/org/jenkinsci/plugins/dockerbuildstep/util/CommandUtilsTest.java

Added support for creating containers with CPU shares (relative weight) and memory limit options. These options are useful for scheduling containers on a cluster.

CPU shares and memory limit options for creating a container

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerPostBuilder.java
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/DockerPostBuilder/config.jelly

A failing build step stops the execution of the rest of the build steps, including a Docker stop/remove build step. Hence cleaning up (stopping and removing) Docker containers in a post build step is needed to keep the Docker host 'healthy'.

Post build step to stop and remove Docker containers

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CommitCommand.java

I noticed that most other parameters will substitute environment variables like $BUILD_TAG, but the commit command only did it for the containers ids.
I wanted to be able to commit a container with a unique tag so that it could be inspected later.

Add environment variable substitution to all commit command parameters

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/ExecCreateAndStartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/ExecStartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/util/CommandUtils.java
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/ExecCreateAndStartCommand/config-detail.jelly

I wanted to make use of existing exec steps, but with the create and start steps separate I couldn't see how to pass the exec id from the create to the start steps. I considered exposing the ids as variables, but instead decided combine the steps. Is there ever a scenario where you would want to run them seperate?
I have left the existing steps for backwards compatibility, although I'm not sure that anyone can use them in their current form. I'm happy to get rid of them if required.
I have also added the ability to log the the streamed response from the Docker API as I wanted to have visibility of this. It would be better if this was configurable, but that can be done later if it is required.

Introduce a new exec command that combines create and start exec

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateContainerCommand.java

Hi,
I couldn't create and start a container for Maven like specified in [the description of the official image](https://hub.docker.com/_/maven/).
I had this result :
```
[Docker] ERROR: command 'Start container(s)' failed: Cannot start container my-maven-project: [8] System error: exec: "mvn clean install": executable file not found in $PATH
```
I think the simplest way to correct it is to consider the command string like an array splited by spaces.
In a second time, it will be a good idea to consider syntax like ["mvn","clean","install"].
Regards,
BorX

Correction in CreateContainerCommand - Command with multiple args

---

pom.xml

Hey folks,
The latest Docker remote api is throwing an out of date client error when using the plugin.  Upgrading the docker-commons dependency resolves this.

upgraded docker commons dependency to 1.2

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java

The build step display text is currently "Execute Docker container", and that is from back when the plugin did not do as much.  It is a confusing selection when you also have other docker plugins installed.

Clarify the build step display text

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerPostBuilder.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveAllCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveCommand.java
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/DockerPostBuilder/config.jelly
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveAllCommand/config-detail.jelly
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveCommand/config-detail.jelly

Hi,
1. Added 'force' option to RemoveCommand, RemoveAllCommand and DockerPostBuildStep. Remove in 'force' mode kills the container (if running) beforehand, so no need to call client.killContainerCmd before removal anymore. 
2. Added getters to 'removeVolumes' option, otherwise Jenkins won't display the current value of this option.

'Force' option added to commands for container removal

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand.java

When lefts Build arguments empty, the build process raise an error:
> [Docker] INFO: Parsing buildArgs: 
> [Docker] ERROR: Invalid format for . Buildargs should be formatted as key=value
when I fill something into the Build arguments form, like:
> foo=bar
the error disappeared.

Cover the case that buildArgs value is empty string.

---

src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/StartCommand/config-detail.jelly

Added rudimentary description about the required format to to use the "Wait for ports" feature in the start command.

Update config-detail.jelly: Document "Wait for ports" format

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerPostBuilder.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CommitCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateContainerCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/DockerCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/ExecCreateAndStartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/ExecCreateCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/ExecStartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/KillCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/PullImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/PushImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveAllCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/RemoveImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/RestartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/SaveImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StartByImageIdCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StopAllCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StopByImageIdCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StopCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/TagImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/util/Resolver.java

Currently, the plugin can't cope well with Jenkins Slaves as it's described in [this issue](https://issues.jenkins-ci.org/browse/JENKINS-24071).
This changeset contains modifications that provide basic infrastructure for the ```DockerCommands``` to perform their task on slave nodes as well:
- the ```Launcher``` is provided for executions, as it's needed to get a ```Channel```.
- the ```DockerBuilder``` and related core functionality got augmented to provide serializable configuration required for the docker commands.
The changeset also contains modifications for the ```CreateImageCommand``` to take advantage of this and be able to work on slaves. Currently, this is the only one I've changed in an attempt to get earlier feedback if this solution is acceptable - and because for us, the this …

Fix for JENKINS-24071: Docker build step tries to build on master and not slave

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/remote/CreateImageRemoteCallable.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/remote/PullImageRemoteCallable.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/remote/PushImageRemoteCallable.java

1. Create/build wasn't logging anything before
2. Logs for push used to look like:
```
[Docker] INFO: BuildResponseItem[stream=
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
[Docker] INFO: BuildResponseItem[stream= ---> d031200b6d71
,status=<null>,progressDetail=<null>,progress=<null>,id=<null>,from=<null>,time=<null>,errorDetail=<null>,error=<null>,aux=<null>]
```
Now they look like:
```
[Docker] INFO:  ---> Using cache
[Docker] INFO:  ---> 681d455e2526
```

fix console logging of build/pull/push commands

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/remote/CreateImageRemoteCallable.java
src/main/resources/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand/config-detail.jelly

Added option to force pull base image before build docker image. 
It might be useful when user builds custom image based on image that may be updated in future, e.g. node:lts, python:3, jenkins:lts.

Add option to force pull base image before build docker images

---

pom.xml

Enable GitHub documentation for this plugin on plugins.jenkins.io
according to the blog post
https://jenkins.io/blog/2019/10/21/plugin-docs-on-github/
This will migrate the plugin documentation to GitHub as the wiki
is currently set to read-only and the documentation on GitHub is
far more detailed anyway.

Update pom.xml to use GitHub URL

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateImageCommand.java

When using the create image command, build args with '=' will not be parsed correctly.
For instance, with these parameters : `test_url=http://example.com?test=something;another_arg=value`
Currently the `test_url` arg will cause this error: ` ERROR: Invalid format for test_url=http://example.com?test=something. Buildargs should be formatted as key=value`. Despite the value being acceptable, there is no way to have the '=' symbol anywhere in a build arg.
This PR fixes this.

Fix parsing of build args with '='

---

pom.xml
src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerCredConfig.java

Upgrade docker java to 3.2.7 and use the http client as transport instead of Jersey
The docker build step plugin uses Jersey as the transport to communicate with docker
This causes problems with new version of Jenkins because of conflicts with jersey versions as can be seen at https://github.com/vjuranek/docker-build-step-plugin/issues/64
This PR aims to use new version of docker java and use the http client version 5 as transport instead of Jersey 
- [x ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x ] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [x ] Link to relevant issues in GitHub or Jira
I built the project, uploaded it to my Jenkins and tried to pull …

Upgrade docker java to 3.2.7 and use http client as transport instead of Jersey

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/CreateContainerCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StartByImageIdCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/StartCommand.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/remote/CreateContainerRemoteCallable.java
src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/remote/StartContainerRemoteCallable.java

- Fix for [JENKINS-65498](https://issues.jenkins.io/browse/JENKINS-65498) that will prevent an exception from being thrown.
- Fix for [JENKINS-67504](https://issues.jenkins.io/browse/JENKINS-67504) that skips unknown fields instead of throwing an exception.

Fixes for JENKINS-65498 and JENKINS-67504

---

pom.xml
src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerPostBuilder.java

This change will make the option which stops and removes the Docker container in the Post Build step available in a Maven project job type. Before, it was only available in FreeStyle and Multi-Configuration projects.

Added Maven job type in Post Build step

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/cmd/SaveImageCommand.java

Replaces a usage of the deprecated `org.apache.commons.httpclient.HttpStatus` with a non-deprecated equivalent from the Java Platform.
CC @vjuranek

Replace deprecated usage with non-deprecated equivalent

---

.mvn/extensions.xml
Jenkinsfile
pom.xml
src/main/java/org/jenkinsci/plugins/dockerbuildstep/DockerBuilder.java

Updates to latest dependency chain including the latest Docker Client (backed by Apache HttpClient rather than Netty). Tested interactively by running a Docker pull command in a Jenkins job.

Modernize plugin

---

src/main/resources/org/jenkinsci/plugins/dockerbuildstep/action/DockerContainerConsoleAction/index.jelly

The change proposed replaces the EOL spinner.gif with the drop-in Jelly tag replacement.

Replace EOL spinner.gif

---

src/main/java/org/jenkinsci/plugins/dockerbuildstep/action/DockerContainerConsoleAction.java

[JZlib](https://github.com/ymnk/jzlib) has not been updated since 2013. Since then, [`GZIPInputStream`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPInputStream.html) and [`GZIPOutputStream`](https://docs.oracle.com/javase/8/docs/api/java/util/zip/GZIPOutputStream.html) have been added to the Java 7 API, so it seems more prudent to use those implementations.

Use Java 7 versions of GZIPInputStream and GZIPOutputStream
